services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=root
      - MONGODB_INITDB_ROOT_PASSWORD=super_secure_password
      - MONGO_INITDB_DATABASE=explore-db
    ports:
      - 27017:27017
    volumes:
      - type: bind
        source: ./data
        target: /data/db
      - type: bind
        source: ./init-mongo.js
        target: /docker-entrypoint-initdb.d/init-mongo.js

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "28081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: changeme
      #ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: super_secure_password
      ME_CONFIG_MONGODB_URL: mongo://root:super_secure_password@mongodb:27017/
    depends_on:
      - mongodb
